### ISSUE TITLE
flash command not working

### ISSUE THREAD

**Issue by bkolb** [ladislas/mbed-cmake-template#3]
I tried to use your flash command. First, I noticed that I need to install `openocd`in addition.

Now I am stuck because ` interface/stlink.cfg` cannot be found. Any idea?

**Comment by ladislas** [comment]
The flash command is for ST's boards. Are you using this kind of board?

I think I installed openocd from source with `brew install openocd --head`

**Comment by bkolb** [comment]
Yes, I am using a St board as well. And I installed openocd using brew.
Where is the file supposed to be?

Ladislas de Toldi <notifications@github.com> schrieb am Fr. 1. Jan. 2021 um
20:05:

**Comment by ladislas** [comment]
The file should be somewhere around here:

`/usr/local/Cellar/open-ocd/HEAD-c69b4de/share/openocd/scripts` with the `HEAD-c69b4de` being a little different.

as I said, openocd must be built from source using `--head` -- I just tried it and had an error, so I made a PR to brew/core:

https://github.com/Homebrew/homebrew-core/pull/68165

**Comment by bkolb** [comment]
Ah! Thank you. The head version indeed seems to work! Great!
